### ISSUE TITLE
Sessions are broken

### ISSUE THREAD

**Issue by pulliam** [pulliam/spottygram#1]
Hi Phil (or Anna or Sung)!
My sessions are not quite working. I can log in with a wrong password and I couldn't figure out why. Also, the sessions last SO little I need to keep logging in. Can you help me fix this issue? Ive tried so many things already.

Thanks!

**Comment by phlco** [comment]
@pulliam please include links the the files in question or some code snippets. also let us kmow what you've already tried

**Comment by pulliam** [comment]
@phlco @sungchoi @annarankin 

https://github.com/pulliam/spottygram/blob/master/app.js
https://github.com/pulliam/spottygram/blob/master/views/login.ejs

``` javascript
var authenticate = function(username, password, callback) {
      db.collection('sessions').findOne({ username: username }, 
        function(err, data) { 
          if (err) { throw err; }
          console.log(data);
          bcrypt.compare( password, data.password_digest, function(isMatch) {
          console.log( 'password is ' + data.password_digest );
          if (isMatch) {
            callback(data);
            console.log('password match')
          } else {
            callback(false);
          }
        })
      });
    };
```

``` javascript
app.post('/login', function(req, res) {
      console.log('username: ' + req.body.username);
      console.log('password: ' + req.body.password);


      authenticate(req.body.username, req.body.password, 
        function(user){
          if (user) {
              req.session.username = user.username;
              req.session.userID = user._id;
              res.redirect('/');
          } else {
              res.redirect('/login');
          }
        });
    });
```

``` javascript
    app.post('/user', function(req, res){
      if (req.body.password.length > 7 && req.body.password === req.body.password_confirm) {
        var password = bcrypt.hashSync(req.body.password, 8);
        var username = req.body.username;
        db.collection('sessions').insert({username: username, password: password}, 
          function(err, result){
            console.log(result);
          });
        authenticate(req.body.username, req.body.password, function(user){
          if (user){
            req.session.username = user.username;
            req.session.userID = user._id;
            res.redirect('/all');
          } else {
            res.redirect('/');
          }
        });
      }
    });
```

This is what I have on sessions. It is "logging in" - A session is being stored in the cookies and I have access to the pages where I can only access logged in. What happens though is that if you try to log in with a non-existent user or use some wrong password, you will still log in successfully. I am guessing the problem is with the authentication and bcrypt perhaps. Or maybe with the database? It is storing in the database though when a new user is created. That's why I suspect it's some lack of knowledge on how to use sessions in my part, and maybe the bcrypt use. I tried a lot to figure out what could be going wrong, but Im not so familiar with sessions and all my trials to learn didn't work because everything seems to work fine and I get no errors. That's why Im not sure how to fix it.

**Comment by annarankin** [comment]
Hey Thais! I left a message on your issue from before about your authenticate method - also, re: sessions not lasting long - are you being logged out, or is something else happening? When are you running into this problem?
