### ISSUE TITLE
How to make session longer

### ISSUE THREAD

**Issue by pulliam** [pulliam/spottygram#4]
My sessions are finishing every like minute. I need to keep logging in. Any advice? I feel like it's the maxAge but Im not sure Im im right. This is my code:

``` javascript
app.use(session({
  cookie: { maxAge: 80000 },
  secret: 'secret',
  resave: true,
  saveUninitialized: false,
  store: new MongoStore({url: mongoUrl})
}));
```

**Comment by annarankin** [comment]
Hey Thais! I'd just get rid of the `cookie: {maxAge: 80000},` option in
your session's options hash - your sessions are then set to be only 80
seconds long! If you leave that out, your sessions will not expire.

**Comment by pulliam** [comment]
Thank you! <3
